### ISSUE TITLE
Request to add prefix_list_id output for vpc endpoint

### ISSUE THREAD

**Issue by ioancatana** [terraform-aws-modules/terraform-aws-vpc#1002]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? 
  - Yes ✅: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpc_endpoint#prefix_list_id

## Is your request related to a problem? Please describe.
We are using Lambda functions, and to be able to use VPC Endpoints on lambda, we need to add prefix_list_id to Lambda SG Egress rule.

## Describe the solution you'd like.
Add output of prefix_list_id for vpc-endpoints module

## Describe alternatives you've considered.
We are using data to retrieve the prefix_list_id for endpoint created, but we would like to have this feature added directly to module.

## Additional context
path: `terraform-aws-vpc/modules/vpc-endpoints/outputs.tf`
You can add this to outputs.tf: 
```hcl
output "prefix_list_id" {
  description = "The prefix list ID of the exposed AWS service. Applicable for endpoints of type Gateway."
  value = try(aws_vpc_endpoint.this[0].prefix_list_id, null)
}
```

**Comment by magreenbaum** [comment]
You can access the `prefix_list_id` from the existing output since it includes all endpoint attributes. For example, in the complete example for the s3 endpoint [here](https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/c467edb180c38f493b0e9c6fdc22998a97dfde89/examples/complete/main.tf#L104), you can retrieve it with `module.vpc_endpoints.endpoints["s3"].prefix_list_id`.

**Comment by bryantbiggs** [comment]
closing with the excellent guidance from @magreenbaum !
