### ISSUE TITLE
Support uneven number of subnets per AZ

### ISSUE THREAD

**Issue by jhenry82** [terraform-aws-modules/terraform-aws-vpc#140]
I'm trying to model an existing VPC setup using this module. It has a bunch of subnets scattered across 5 AZ's in us-east-1. Some of these are private, some are public. There are not the same number of public and private subnets in each AZ.

As far as I can tell, this cannot be recreated using the module. Is that correct? I'll need some additional subnet resources outside of the module to add the ones that don't fit?

Example:
us-east-1a: 1 public subnet, 2 private subnets
us-east-1c: 4 public subnets, 3 private subnets

I can't come up with a combo of azs, public_subnets, and private_subnets that would mimic this. But I'm new to Terraform so it's also possible I am just wrong about this :) 

Could we maybe add some new optional inputs like pubic_azs, private_azs and intra_azs that would take precedence over azs if defined? That should be a backward compatible way to allow this.

**Comment by antonbabenko** [comment]
Hi Jon,

Thanks for this feature request. You are right, it is not possible to implement an uneven number of subnets per AZ and this module won't have this feature supported, because of the complexity multiplied by a number of NAT gateways, subnet groups, etc.

I think you can use this module to create the majority of your resources and create the rest using outputs from this module and individual resources.

In the future, we may extend this module to support adoption of existing VPCs (created using this module or without it) and append resources like subnets, NAT gateways, routes to it.

Closing this issue for now. Please open a new one, if you have other questions related to this module.
