### ISSUE TITLE
`default_route_table_tags` not wired up?

### ISSUE THREAD

**Issue by lorengordon** [terraform-aws-modules/terraform-aws-vpc#146]
I see `default_route_table_tags` in variables.tf and in the readme, but when I tried to use it nothing happened. Looks like it's not wired up in main.tf?

```
> grep -c default_route_table_tags main.tf
0
```

**Comment by antonbabenko** [comment]
Good catch!

[v1.37.0](https://github.com/terraform-aws-modules/terraform-aws-vpc/releases/v1.37.0) is out.

**Comment by lorengordon** [comment]
5 min! That's gotta be a record! 😂 You're a rockstar @antonbabenko

**Comment by lorengordon** [comment]
Oh you just removed it. lol. How about if I work a pr that adds support later today?

**Comment by antonbabenko** [comment]
We have had some challenges with `aws_default_route_table` resource which turned out to be pretty advanced (it probably requires another lifecycle) and it gives little benefits, so it was added and then it was removed from this module.

Search code base of this module for this resource and there were some discussions in issues about it for some time.

**Comment by lorengordon** [comment]
I remember seeing some of that traffic, but I thought it was before all the default VPC management options were fleshed out, so I thought this was _re-added_ with those extra options. I'd like this option just for the sake of consistency. I'll poke around and try to better understand what the problem was before (I never encountered any problems when using this in the earlier support).
