### ISSUE TITLE
FEATURE: Change default subnet Name tag

### ISSUE THREAD

**Issue by lgooch** [terraform-aws-modules/terraform-aws-vpc#153]
To easily differentiate between the various subnets that are created it would be useful to not have the blanket Name tag applied. Instead it would be useful to have the name for each subnet be [subnet_type] [availability_zone] e.g. Private 1a, Public 1a etc

an example main.tf that would set all Name tags of the subnets to Prod
```
module "vpc" {
  source = "./terraform-aws-vpc"

  name = "Prod"`

  cidr = "10.1.0.0/16"

  azs                 = ["eu-west-2a", "eu-west-2b", "eu-west-2c"]
  private_subnets     = ["10.1.0.0/19", "10.1.64.0/19", "10.1.128.0/19"]
  public_subnets      = ["10.1.32.0/20", "10.1.96.0/20", "10.1.160.0/20"]

  tags = {
    Owner       = "user"
    Environment = "Production"
    Name        = "Prod"
  }
}
```

**Comment by antonbabenko** [comment]
Tagging of individual types of resources is already supported. Maps of tags are being merged and since you speficy `Name` in `tags` argument it will have the highest priority.

Check this example:
https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/78584e5198eabaa0fda33f8f780eca0fa183f4fe/examples/simple-vpc/main.tf#L19-L30

There are many different arguments related to tagging.

Closing this issue.
