### ISSUE TITLE
Count variable inside module "vpc"

### ISSUE THREAD

**Issue by rohityadav225** [terraform-aws-modules/terraform-aws-vpc#187]
Is there a way to use `count` variable inside module block ? 
I am trying to do the following, is there a better way to do it ?
```
module "vpc" {
  source = "terraform-aws-modules/vpc/aws"

  name = "${terraform.workspace}-vpc"
  cidr = "${var.vpc_cidr_start_ip}"

  count = "${var.az_count}"
  
  azs              = "${element(split(", ", var.aws_azs), count.index)}"
  public_subnets = "${var.vpc_cidr_base}${lookup(var.public_subnet_cidrs, format("zone%d", count.index))}"
  private_subnets  = "${var.vpc_cidr_base}${lookup(var.private_subnet_cidrs, format("zone%d", count.index))}"
  database_subnets = "${var.vpc_cidr_base}${lookup(var.database_subnet_cidrs, format("zone%d", count.index))}"

  create_database_subnet_group = true

  enable_nat_gateway   = true
  enable_vpn_gateway   = true
  reuse_nat_ips        = true
  external_nat_ip_ids  = ["${aws_eip.nat.*.id}"]
  enable_dns_support   = true
  enable_dns_hostnames = true

  tags = "${merge(var.global_tags,map("stack","${terraform.workspace}"))}"
}
```

**Comment by antonbabenko** [comment]
Hi Rohit!

You probably don't want to make it look so complex and use a fixed list of values to pass as arguments to the module.

If you want to make something like you are describing you can use things like `null_resource` to generate values of specific type dynamically. It will very likely be unmaintainable in a long run, so try to avoid this.

`count` is not a valid name of the argument in this module and should not be used, because it is a reserved argument in the upcoming version of Terraform 0.12.
