### ISSUE TITLE
suffix naming is not applied

### ISSUE THREAD

**Issue by aosman-tibco** [terraform-aws-modules/terraform-aws-vpc#190]
The VPC created from the following has no suffixes applied to the subnet resources, only the name variable is used.

```hcl
module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "1.46.0"

  name = "${var.environment}"
  cidr = "${module.network_generation.vpc_cidr}"

  azs             = "${module.network_generation.availability_zones}"
  private_subnets = "${module.network_generation.private_subnets}"
  public_subnets  = "${module.network_generation.public_subnets}"

  enable_nat_gateway      = true
  single_nat_gateway      = false
  one_nat_gateway_per_az  = true

  enable_dns_hostnames      = true
  enable_dns_support        = true
  enable_dynamodb_endpoint  = true
  enable_s3_endpoint        = true

  private_subnet_suffix = "private"
  public_subnet_suffix  = "public"

  tags = {
    Name = "${var.environment}"
    Environment = "${var.environment}"
  }
}
```

**Comment by adamrt** [comment]
@aosman-tibco I ran into this as well. It turned out it was because I was setting `module.vpc.tags.Name` manually, which I can see you are doing as well. 

I removed the `Name = "${var.environment}"` tag that you have there and did a `terraform plan` and it renames all of them from like this (for each resource)
`tags.Name: "staging-vpc" => "staging-vpc-us-east-2a"`.

Everything working as expected. Additionally, you can remove `private_subnet_suffix = "private"` and `public_subnet_suffix  = "public"` as those are the defaults.

**Comment by aosman-tibco** [comment]
Thanks for the tip! I should have known setting the Name tag would override it.
