### ISSUE TITLE
allow dedicated routing tables for each private subnet

### ISSUE THREAD

**Issue by ebarault** [terraform-aws-modules/terraform-aws-vpc#200]
Currently, the following [lines](https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/main.tf#L99) make the assumption that a single routing table will be set up per NAT gateway, hence associating at best all subnets of a single AZ with the same routing table
```
resource "aws_route_table" "private" {
  count = "${var.create_vpc && local.max_subnet_length > 0 ? local.nat_gateway_count : 0}"
  vpc_id = "${local.vpc_id}"
  ...
}
```

but what if someone wants to dedicate a routing table per private subnet in order for example to isolate routing rules towards overlapping CIDRs accessed remotely through VPN gateways?

what do you think of an option to allow as many routing tables as there are subnets ?

**Comment by ebarault** [comment]
by a matter of fact,[ this once was the case ](https://github.com/terraform-aws-modules/terraform-aws-vpc/commit/3ddef14f9183bb2afbb39cddb206dfc21e65f7b1#diff-7a370d8342e7203b805911c92454f0f4R73)where as many routing tables were created as private subnets

**Comment by ideasculptor** [comment]
The code seems to create n routing tables, as of 2.15, but it does NOT add all n routing table to the list of routing tablkes in the output, so it does no good having many routing tables because they still cannot actually be used or accessed in any way, without manually looking up their ids.

```
private_route_table_ids = [
  "rtb-002fa905d2a50b565",
]
private_subnet_arns = [
  "subnet-0cde313d8948dde3e",
  "subnet-024d18d9d30cd20ef",
]
private_subnets = [
  "subnet-0cde313d8948dde3e",
  "subnet-024d18d9d30cd20ef",
]
private_subnets_cidr_blocks = [
  "10.11.1.0/24",
  "10.11.2.0/24",
]
public_network_acl_id = acl-0d428762d954e8faf
public_route_table_ids = [
  "rtb-07ddc62d083a42e34",
]
public_subnet_arns = [
  "arn:aws:ec2:us-west-1:312506926764:subnet/subnet-0a398c612600becd1",
  "arn:aws:ec2:us-west-1:312506926764:subnet/subnet-010dd7c0e5e50af53",
]
public_subnets = [
  "subnet-0a398c612600becd1",
  "subnet-010dd7c0e5e50af53",
]
public_subnets_cidr_blocks = [
  "10.11.101.0/24",
  "10.11.102.0/24",
]
```

Note that the number of route tables is 1 for each type of subnet.  But looking at the console, I get one for each actual subnet.
![Screen Shot 2019-09-16 at 11 46 34 AM](https://user-images.githubusercontent.com/484573/64984427-b3c12c00-d877-11e9-88d1-ae974f990d45.png)

You can clearly see that there are 2 route tables for 2 public subnets.  They have identical names, but they do NOT share an ID. Only the first one shows up in the outputs of the module.

**Comment by lgallard** [comment]
+1  

Current implementation doesn't allow the centralized deployment model for AWS Network Firewall where [each Transit Gateway subnet requires a dedicated VPC route table to ensure the traffic is forwarded to firewall endpoint within the same AZ. ](https://aws.amazon.com/blogs/networking-and-content-delivery/deployment-models-for-aws-network-firewall/#:~:text=Each%20Transit%20Gateway%20subnet%20requires%20a%20dedicated%20VPC%20route%20table%20to%20ensure%20the%20traffic%20is%20forwarded%20to%20firewall%20endpoint%20within%20the%20same%20AZ.)

It would be great having a flag to allow creating a route table for each VPC.

**Comment by bryantbiggs** [comment]
hi all, - this should be addressed in the next version which is under development here https://github.com/clowdhaus/terraform-aws-vpc-v4/tree/main/modules/subnets
