### ISSUE TITLE
managing of public / private route tables is inconsistent

### ISSUE THREAD

**Issue by tbugfinder** [terraform-aws-modules/terraform-aws-vpc#211]
https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/8e2f50e6c8f8fd8b0abcaf2c4150d7446276fcaa/main.tf#L452-L457

https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/8e2f50e6c8f8fd8b0abcaf2c4150d7446276fcaa/main.tf#L487-L492

For private subnet(s), each subnet gets a dedicated route table (1:1 association) vs.
for public subnet(s) there is a single route table with associated subnets (1:n association).

-- this is inconsistent --
Is there any specific reason for that?

.

**Comment by ironick09** [comment]
You can only have one internet gateway per VPC, therefore, you only need one public route table that all your `public_subnets` are associated with. They are inherently highly-available (across AZs) per the AWS documentation: https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Internet_Gateway.html

You cannot even have more than one Internet Gateway associated with a VPC in AWS (I just tried to associated a second one with a VPC that already had an Internet Gateway associated with it). 

The implementation here is _not_ inconsistent. 

Also, for `private_subnets` the association depends on if you set `single_nat_gateway` or not. If you set `single_nat_gateway = true` then you will only have one private route table, associated with a single NAT gateway, and all your `private_subnets` are associated with this single route table. This becomes a N:1 association (many private subnets to one private route table, that is associated with a single NAT gateway). 

We know this because on the following line:
https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/8e2f50e6c8f8fd8b0abcaf2c4150d7446276fcaa/main.tf#L456
When `var.single_nat_gateway` evaluates to true, `0` is used to replace `*` and the `route_table_id` becomes `"${aws_route_table.private.0.id}"` for all `private_subnets`.

**Comment by tbugfinder** [comment]
Thank you very much. I didn't see or relate that single_nat_gateway has that implication. Reading your post it indeed makes sense and options are there.

Indeed it makes sense to think about redundancy of NAT gateways as those are tight to AZs.
https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html

**Comment by ideasculptor** [comment]
However, the handling is still entirely incorrect.  When I look at the outputs of this module, I get a single route table id for n private subnets, and I get a single route table id for n public subnets.  But if I look at the AWS console, it is quite clear that there is a route table PER SUBNET.  When I attempt to use the 'list' of route table ids to set up peering, I cannot connect any subnet except the first from each of public and private.  This is totally broken

```
public_network_acl_id = acl-0d428762d954e8faf

**public_route_table_ids = [
  "rtb-07ddc62d083a42e34",
]**

public_subnet_arns = [
  "arn:aws:ec2:us-west-1:312506926764:subnet/subnet-0a398c612600becd1",
  "arn:aws:ec2:us-west-1:312506926764:subnet/subnet-010dd7c0e5e50af53",
]
public_subnets = [
  "subnet-0a398c612600becd1",
  "subnet-010dd7c0e5e50af53",
]
public_subnets_cidr_blocks = [
  "10.11.101.0/24",
  "10.11.102.0/24",
]

**private_route_table_ids = [
  "rtb-002fa905d2a50b565",
]**

private_subnet_arns = [
  "subnet-0cde313d8948dde3e",
  "subnet-024d18d9d30cd20ef",
]
private_subnets = [
  "subnet-0cde313d8948dde3e",
  "subnet-024d18d9d30cd20ef",
]
private_subnets_cidr_blocks = [
  "10.11.1.0/24",
  "10.11.2.0/24",
]

```

One need only look at the console to see that there is a routing table PER SUBNET and that it will be necessary to have references to all of them.  Whatever logic is being used to resolve which routing tables to put in the outputs, it is not correct
