### ISSUE TITLE
enable_dns_support default

### ISSUE THREAD

**Issue by thejmazz** [terraform-aws-modules/terraform-aws-vpc#25]
I was confused by this, wondering why I could not `curl google.com` for example when entering an instance in my VPC. Looking further and I found [this](https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/85a47cb3a9a21c1843b0123f0db3cc36d9f3c7f6/variables.tf#L53-L56):

```terraform
variable "enable_dns_support" {
  description = "Should be true if you want to use private DNS within the VPC"
  default     = false
}
```

Should that not be `true`, and `false` if you would be using your own authoritative DNS server? The default seems to be `x.x.x.2` on the VPC, and when `dig google.com` I was getting timeouts until setting `enable_dns_support = true`.

**Comment by antonbabenko** [comment]
For historical reasons this module has been uplifted from [tf_aws_vpc](https://github.com/terraform-community-modules/tf_aws_vpc) with the goal of keeping backward compatibility, because it is NOT possible to specify _not latest_ version of the module from Terraform registry.

I agree this should be changed and the default value for `enable_dns_support` should be `true`, as specified in the [official documentation](https://www.terraform.io/docs/providers/aws/r/vpc.html#enable_dns_support). We can do this when Terraform 0.11+ has a possibility to specify versions.

PS: Thanks for opening an issue!

**Comment by antonbabenko** [comment]
[v1.5.0](https://github.com/terraform-aws-modules/terraform-aws-vpc/releases/tag/v1.5.0) is released
