### ISSUE TITLE
Could we add the option to use a NAT instance rather than a NAT gateway in the VPC?

### ISSUE THREAD

**Issue by bmacauley-reward** [terraform-aws-modules/terraform-aws-vpc#250]
NAT gateways start to get expensive when you have many accounts and VPC's

Would it be possible to add the option to use the older NAT instance instead of the NAT gateway? If had the option to set the instance size as well, we could scale down to micro's or nano's

https://www.theguild.nl/cost-saving-with-nat-instances/

Jetbrains example...
https://github.com/jetbrains-infra/terraform-aws-vpc-with-private-subnets-and-nat

**Comment by sirket** [comment]
You may be better off simply using single_nat_gateway = true rather than running NAT instances. An undersized NAT instance coupled with a developer who suddenly decides to push a bunch of traffic can result in dropped traffic and hard to troubleshoot problems. A single NAT gateway won't have that issue while also saving money. For a dev or testing account the loss of redundancy shouldn't pose any problems. For production accounts the problems with NAT instances outweigh any cost savings.

**Comment by bmacauley-reward** [comment]
Agreed... NAT gateways for production

But i would like NAT instances for non-prod....with the ability to turn them off at scheduled times to save cost

**Comment by bonovoxly** [comment]
Custom configurations may require a NAT instance. This would be a useful feature.

**Comment by antonbabenko** [comment]
This is out of scope for this module as mentioned in #281 

Closing this issue.
