### ISSUE TITLE
Default VPC Security Group Tags

### ISSUE THREAD

**Issue by e-moshaya** [terraform-aws-modules/terraform-aws-vpc#257]
Is there a way to set the vpc's default security group tags? I'm not referring to the default VPC security group but the default security group for the current VPC created through this module.

**Comment by sirket** [comment]
You could simply add this to main.tf in the module:

resource "aws_default_security_group" "default" {
  vpc_id = "${aws_vpc.this.id}"

  ingress {
    protocol  = -1
    self      = true
    from_port = 0
    to_port   = 0
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

   tags = "${merge(map("Name", format("%s", var.name)), var.tags, var.vpc_tags)}"
}

That said- the default VPC security group really should not be used for anything so leaving off the tags might make sense.

**Comment by ndench** [comment]
I use the default security group for most things because it allows everything in the vpc to communicate. I only create other security groups when I want the outside world to communicate with my infrastructure (ie. ssh, web, etc).

Can confirm that the `aws_default_security_group` workaround from @sirket works well but it would be nice for the module to attach tags to the security group. If you're creating multiple VPC's in the same region, it quite hard to tell their default security groups apart unless they're tagged.

**Comment by DrFaust92** [comment]
closed by #382
