### ISSUE TITLE
Create multiple public subnet groups using Terrafrom

### ISSUE THREAD

**Issue by sanooprajps** [terraform-aws-modules/terraform-aws-vpc#371]
Good day all!
We are trying to achieve the following requirement using Terraform.

We need to have multiple public subnets with different Tag names across three AZs as below.
What is the best way to achieve this using terraform modules. 

AZ1				AZ2				AZ3
---				---				---
subnet_public_group1_1a		subnet_public_group1_1b		subnet_public_group1_1c
subnet_public_group2_1a		subnet_public_group2_1b		subnet_public_group2_1c
subnet_public_group3_1a		subnet_public_group3_1b		subnet_public_group3_1c

We currently have an approach of using separate resources defined for each subnet groups(subnet_public_group1, subnet_public_group2, subnet_public_group3) in Terraform modules.

Is there a better way to achieve this using the existing terraform modules(aws_subnet resource for public network)?

Also, we are going to associate single route table to all these subnets created above.

Any help is appreciated.

**Comment by bryantbiggs** [comment]
hello @sanooprajps - I'm struggling following what you are trying to achieve. Are you trying to use `subnet_public_group1_xx` instead of the naming scheme offered by the module? I would suggest approaching your problem differently - the name of the subnets is meant to be descriptive as to their end use (public, private, elasticache, redshift, etc.) If you rely on the name for some reason, I would suggest you inject your necessary meta information as tags and query off of tags. You can tag the different subnet groups as needed (i.e. - `public_subnet_tags`, `private_subnet_tags`, etc.)

**Comment by strowi** [comment]
Hi,

i think we have a similar use-case.
We're trying to follow a 3-subnet-layer setup (public, private, data/persistence).

Therefore we'd need 2 private subnets in each az. But with the default naming, we can't really differentiate those private + data subnets.

I think #379  would be really helpful to @sanooprajps and our use-case.

**Comment by blunt1973** [comment]
Yes, we just want to create multiple private subnets with the custom name too, but look so hard now

**Comment by xeivieni** [comment]
Hi, did anyone find a way to do this with the module ?

**Comment by hemzet** [comment]
You may just make use of private_subnets and database_subnets. This results in two different private subnets per az.

**Comment by dusansusic** [comment]
Not stale

**Comment by bryantbiggs** [comment]
hi all, this should be addressed in the next version which is under development here https://github.com/clowdhaus/terraform-aws-vpc-v4/tree/main/modules/subnets

**Comment by frankbecker** [comment]
Did this ever get resolved? I wish we could create multiple groups of subnets, like multiple private and public groups?
