### ISSUE TITLE
VPC endpoint creation error - DuplicateSubnetsInSameZone

### ISSUE THREAD

**Issue by gvk777** [terraform-aws-modules/terraform-aws-vpc#451]
Hi,

I am trying to create vpc endpoint for the 1st time using cloud formation stack template in the terraform script, but I am getting the below error. Please help

Terraform Version:0.12.20

Error: ROLLBACK_COMPLETE: ["The following resource(s) failed to create: [SSMMessagesEndpoint, TrendPrivateHostedZone, SSMEndpoint, TrendEndpoint, EC2MessagesEndpoint]. . 
Rollback requested by user." "Resource creation cancelled" "Found another VPC endpoint subnet in the availability zone of subnet-XXXXX. 
 "Found another VPC endpoint subnet in the availability zone of subnet-XXXX. 
VPC endpoint subnets should be in different availability zones supported by the VPC endpoint service.
 (Service: AmazonEC2; Status Code: 400; Error Code: DuplicateSubnetsInSameZone; Request ID: XXXXXX)".

I have total 3 subnets, 1 public and 2 private. It is saying the public subnet is already having a vpc endpoint. I am new to the terraform and aws. Please help.

**Comment by bryantbiggs** [comment]
hi @gvk777, this sounds like its unrelated to the vpc module in this project. the error you are facing is because you can only have one vpc endpoint for a specific service in a subnet and it appears you are trying to launch another vpc endpoint of the same service where one already exists in the subnet. @antonbabenko can close

**Comment by gvk777** [comment]
Thanks @bryantbiggs Bryan . I am able to resolve it. You are right I was doing the same.

**Comment by wavemoran** [comment]
I'm getting the same `DuplicateSubnetsInSameZone` error while trying to add some additional subnets to my VPC, since the `ecr_api_endpoint_subnet_ids` variable by default tries to reference _all_ private subnets.

How do I get `ecr_api_endpoint_subnet_ids` to only reference private subnets 0-2 from the output list?
