### ISSUE TITLE
Describe how to update tfstate file after migration to the registry

### ISSUE THREAD

**Issue by antonbabenko** [terraform-aws-modules/terraform-aws-vpc#5]
Include instructions from this comment: https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/4#issuecomment-332380572

**Comment by robinbowes** [comment]
I've just run into this (switching to use the new module with live resources that will be destroyed if I run apply).

I found I had to do the following (I'm using terragrunt, but exactly the same commands will work with terraform too):

```
terragrunt state mv module.vpc.aws_internet_gateway.mod module.vpc.aws_internet_gateway.this

terragrunt state mv module.vpc.aws_eip.nateip[0] module.vpc.aws_eip.nat[0]
terragrunt state mv module.vpc.aws_eip.nateip[1] module.vpc.aws_eip.nat[1]
terragrunt state mv module.vpc.aws_eip.nateip[2] module.vpc.aws_eip.nat[2]

terragrunt state mv module.vpc.aws_nat_gateway.natgw[0] module.vpc.aws_nat_gateway.this[0]
terragrunt state mv module.vpc.aws_nat_gateway.natgw[1] module.vpc.aws_nat_gateway.this[1]
terragrunt state mv module.vpc.aws_nat_gateway.natgw[2] module.vpc.aws_nat_gateway.this[2]

terragrunt state mv module.vpc.aws_vpc.mod module.vpc.aws_vpc.this
```

I was then left with the following resources that were destroyed and re-created (which didn't cause me a problem because I am not using them):

```
module.vpc.aws_db_subnet_group.database
module.vpc.aws_elasticache_subnet_group.elasticache
```

The remaining changes were non-destructive (changes to `tags.Name` only).

**Comment by michalschott** [comment]
I'm using flat terraform v.0.10.7, you don't have to provision resource indexes:

```
terraform state mv module.vpc.aws_vpc.mod module.vpc.aws_vpc.this
terraform state mv module.vpc.aws_nat_gateway.natgw module.vpc.aws_nat_gateway.this
terraform state mv module.vpc.aws_internet_gateway.mod module.vpc.aws_internet_gateway.this
terraform state mv module.vpc.aws_eip.nateip module.vpc.aws_eip.nat
```

**Comment by antonbabenko** [comment]
Can you guys submit a PR to describe this process in more details for people who are facing the same problems?

**Comment by robinbowes** [comment]
Ah, I see - you can move all the indexed resources in one command, eg. in my case:
```
terragrunt state mv module.vpc.aws_internet_gateway.mod module.vpc.aws_internet_gateway.this
terragrunt state mv module.vpc.aws_eip.nateip module.vpc.aws_eip.nat
terragrunt state mv module.vpc.aws_nat_gateway.natgw module.vpc.aws_nat_gateway.this
terragrunt state mv module.vpc.aws_vpc.mod module.vpc.aws_vpc.this
```

**Comment by willejs** [comment]
I have made a PR https://github.com/terraform-aws-modules/terraform-aws-vpc/pull/52 to revert the names to "mod" instead of "this". Changing the names of the resources is a breaking change and should have gone through a PR process and had the version bumped according to semver perhaps?
We are using this module in around 60 VPCs, and we don't have write access to any state files in any environments, so this sort of manual task does not work for us, and ideally breaking changes should be avoided, especially for trivial ones such as names of resources. "this" vs "mod" isnt really a good case to make this change or provide some commands to manipulate state?

**Comment by antonbabenko** [comment]
Commands to manipulate state file are in [this comment](https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/5#issuecomment-335787341)

**Comment by michalschott** [comment]
How do you update your environments then without write access to state files?

**Comment by antonbabenko** [comment]
Changing state means that you have to change a file. If you can't write to those files how could you update the module?

**Comment by FernandoMiguel** [comment]
It could be a close system changing the state, like jenkins builder.
But that would incredibly risky

**Comment by willejs** [comment]
@michalschott @antonbabenko All terraform interaction is done through CI/CD (in our case concourse). We only allow write access to dev accounts, and we store state in S3.
@FernandoMiguel we use CD pipelines, and have a manual gate to production and some tests around each environment.

**Comment by DrFaust92** [comment]
Closing this (as its a pretty old issue), if anyone is still having an issue with this please open a new issues.
