### ISSUE TITLE
Provider source not supported in Terraform v0.12

### ISSUE THREAD

**Issue by rafaelpirolla** [terraform-aws-modules/terraform-aws-vpc#610]
https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/997cba4053bd8b4a5d2aed528073b8f02c013e93/versions.tf#L6

**Comment by jcseals** [comment]
Hi @rafaelpirolla, I hit the same issue using terraform 12.30 and aws provider pinned to "~> 3.0". I believe it's due to the provider requirements being increased to 3.10 in v2.70.0 of the module. Here are the tag notes:

v2.70.0 …
2021-02-02T20:37:50Z
115e736 Updated CHANGELOG
4b83a66 feat: Upgraded minimum required versions of AWS provider to 3.10

I bumped my module version down to 2.69.0 and the plan went through without error.

Someone can comment if there's a better fix?

**Comment by alievrouw** [comment]
I'm seeing this as well. Curious about a better fix.

**Comment by antonbabenko** [comment]
Unfortunately, we have bumped version requirements for Terraform AWS provider to 3.10 and then we managed to find a workaround and reverted requirements to version `>= 2.70` (use `v2.74.0` or newer of this module).

Terraform 0.12 is not being supported in the module so please upgrade Terraform version to 0.13 or newer to be able to use the latest improvements which we are going to have in this module. We won't backport features into Terraform 0.12 branch once we bump Terraform requirements to 0.13.
