### ISSUE TITLE
Is there a list of the requires AWS permissions you need to run this module?

### ISSUE THREAD

**Issue by baynezy** [terraform-aws-modules/terraform-aws-vpc#687]
## Is your request related to a new offering from AWS?
No

## Is your request related to a problem? Please describe.
I am trying to configure this module, but do not want to give the terraform user excessive permissions. The debug output from this is not helping me work out what the missing permissions are.

## Describe the solution you'd like.
I would like a list of AWS permissions that must be Allowed for this module to function.

## Describe alternatives you've considered.
I have run it with admin privileges and it works as expected. If I restrict privileges then it errors with Encoded authorization failure messages that are unhelpful.

**Comment by antonbabenko** [comment]
Hi Simon,

The list of AWS IAM permissions depends very much on what do you want to create and what services should be called.

There are several solutions you can look into. I think, [iamlive](https://github.com/iann0036/iamlive) is one of the most popular. [Here](https://meirg.co.il/2021/04/23/determining-aws-iam-policies-according-to-terraform-and-aws-cli/) is a blog post describing the approach in detail.

I am closing this issue here since it is not related to the module itself.

**Comment by baynezy** [comment]
@antonbabenko - thank you so much. This is actually incredible. I wish I had known about this months ago.

**Comment by antonbabenko** [comment]
Follow me on [twitter](https://twitter.com/antonbabenko) and [linkedin](https://linkedin.com/in/antonbabenko) where I often share findings like this :)
