### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by jeffnappi** [terraform-aws-modules/terraform-aws-vpc#71]
Just wanted to say thanks for maintaining these modules. Great stuff!

Is there an organization behind managing control and maintenance?

**Comment by antonbabenko** [comment]
Hi Jeff,

Glad that you like it! Kudos to the community!

There is no official organization behind this. I do this on my own and I try to convince clients I work with to use and contribute to these modules as well.

Dozens of people already rely on this code, while some use these repositories for inspiration and implement their own solutions.

Fact: There were more than 850K of provisions in the last month of all Terraform AWS modules I maintain under [terraform-aws-modules](https://registry.terraform.io/modules/terraform-aws-modules) account (even if someone is using CI server to download them all every build it still counts, LOL).

As the majority of [terraform-aws-modules repositories from GitHub](https://github.com/terraform-aws-modules) is already published on the [Terraform Registry](https://registry.terraform.io/modules/terraform-aws-modules/) as **verified**, I have agreed to maintain them properly and keep up-to-date as much as possible.

If people want to contribute new Terraform module, which fits quality requirements (not yet described in a single place, though, my bad), and want to maintain it I will be glad to provide guidelines and grant required access.

Looking ahead, I want to improve the quality, write series of blog posts about using them and increase the number of modules but it is pretty hard to find a sponsor who can invest in open-source activities like this. So instead of pushing to random people and companies, I decided to continue working on stuff I like, talk at conferences and see what happens. 🤞

If there are any questions people want to discuss outside of GitHub issues don't hesitate and send me an [email](mailto:anton@antonbabenko.com)

**Comment by horsey** [comment]
@antonbabenko Please let me know if I can help any way with the modules.

**Comment by antonbabenko** [comment]
Sure, feel free to follow me on [medium](https://medium.com/@anton.babenko) and [twitter](https://twitter.com/antonbabenko) where I write updates regularly.

**Comment by jeffnappi** [comment]
Awesome, I love seeing that. We are just now adopting Terraform - if I build any generic modules that I think would be of value to the community I'll definitely reach out. I'll definitely be writing up a blog post about this and I'll be sure to credit this project for anything we're using :100:

**Comment by conzy** [comment]
Also just want to chime in and say thank you for these high quality modules. I am also using the IAM module manage

**Comment by ayush-sharma** [comment]
Hi @antonbabenko,

My team and I love your work, and I was motivated to share my learnings and published 2 blog posts on your VPC and Security Group modules.

1. https://notes.ayushsharma.in/2020/09/creating-aws-vpcs-in-2-minutes-with-terraform-registry
2. https://notes.ayushsharma.in/2020/09/creating-ready-to-use-aws-security-groups-using-terraform-registry-named-groups-and-named-rules

I hope these help in some way to introduce the modules to new audiences.

Thanks a lot for your work,
Ayush.
