### ISSUE TITLE
Add possibility to add 'route_table_ids' for 'gateway' endpoints as value of variable(vpc output)

### ISSUE THREAD

**Issue by NikitaIvankov1992** [terraform-aws-modules/terraform-aws-vpc#725]
## Describe the solution you'd like.

Hello there :) 

Please let me know wether it's possible to update `vpc-endpoints` module in a way to be able to specify `route_table_ids` for `gateway` endpoint as the variable value?(as it's done for security groups and subnet ids)
Something like the following one

`route_table_ids     = lookup(each.value, "service_type", "Interface") == "Gateway" ? distinct(concat(var.route_table_ids,  lookup(each.value, "route_table_ids", null))) : null`

It makes the module usage more flexible since for example we can use the output value of main `vpc` module

Thank you

**Comment by bryantbiggs** [comment]
hi @NikitaIvankov1992 this is already possible today https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/5f5d8776687e403091a200901b2c452b3d3ad9b6/examples/complete-vpc/main.tf#L97

Because there are only 2 possible gateway endpoints, it doesn't make a lot of sense to add in one additional variable to save users one line of code. If you want, you could put the subnet IDs into a local variable and use that in the gateway endpoint maps for S3 and DynamoDB
