### ISSUE TITLE
[Feature Request] Create security group(s) for the vpc endpoint

### ISSUE THREAD

**Issue by tculp** [terraform-aws-modules/terraform-aws-vpc#780]
## Is your request related to a problem? Please describe.
Certain security group rules need to be set to properly use VPCEs, such as (80, 443, 1026, 1027, 1028, 1031, 2222) for storagegateway, (80 and 443) for most other services, etc.

## Describe the solution you'd like.
This module could provide variables to toggle the creation of security groups that fit the needs of the VPCEs being created.

The module could have the ability to create a shared security group that encompasses the needs of all of its services, and individual security groups that provide access to a specific VPCE.

## Describe alternatives you've considered.
Customizing the module for my purposes

**Comment by tculp** [comment]
un-stale

**Comment by tculp** [comment]
un-stale

**Comment by kderck** [comment]
+1

**Comment by kderck** [comment]
@antonbabenko

**Comment by antonbabenko** [comment]
https://github.com/sponsors/antonbabenko - you are welcome to join if you want to support the maintenance and further development of the modules. :)

**Comment by tculp** [comment]
un-stale

**Comment by kderck** [comment]
unstable

**Comment by tculp** [comment]
un-stale

**Comment by kderck** [comment]
un-stale

**Comment by kderck** [comment]
un-stale

**Comment by bryantbiggs** [comment]
I'm going to close this issue because its just being noisy at this point. I personally don't think this is a great approach, we already have a security group module and adding it here with all the different ports and rule combinations based on which endpoints are selected would just be a bunch of overhead. its been open for almost a year and only 2 upvotes so its not a burning issue. thank you though
