### ISSUE TITLE
Deprecate vpc_classic_link

### ISSUE THREAD

**Issue by marcofranssen** [terraform-aws-modules/terraform-aws-vpc#824]
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: 4.28.0

## Is your request related to a problem? Please describe.

```
╷
│ Warning: Argument is deprecated
│ 
│   with module.vpc.aws_vpc.this,
│   on .terraform/modules/vpc/main.tf line 27, in resource "aws_vpc" "this":
│   27:   enable_classiclink               = var.enable_classiclink
│ 
│ With the retirement of EC2-Classic the enable_classiclink attribute has
│ been deprecated and will be removed in a future version.
│ 
│ (and 3 more similar warnings elsewhere)
╵
```

## Describe the solution you'd like.

Implement a migration path once the classiclink is completely removed from the AWS provider.

## Additional context

Warning shows up since we bumped the AWS provider to 4.28.0.

**Comment by lorengordon** [comment]
Fyi, since this module is setting `enable_classiclink` to `null` by default, there is a chance this is a bug. I've opened an upstream issue. Please give it a 👍 !

https://github.com/hashicorp/terraform/issues/31730

**Comment by bryantbiggs** [comment]
Thank you @lorengordon for that. While that is rather annoying, I'm leaning towards maybe just setting it to null on the argument here in the module. Some could view that as a breaking change, but since AWS made this decision and that is the direction (and I suspect it affects a very, very small segment of users), I'm inclined in making that change since it seems like the easiest path to resolution with the least disruption. @antonbabenko what do you think about setting https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/78f2845ee92364038780893e8d2107d692a163d3/main.tf#L27 to a hardcoded `null`?

**Comment by lorengordon** [comment]
You might as well just remove the argument from the resource, in that case... It's the same effect to terraform and the provider, and less code.

**Comment by lorengordon** [comment]
The harder "backwards incompatible" bit for this module, imo, would be the removal of the _variable_, `var.enable_classiclink`. Since for any user that is setting that variable in their config, even if `false` or `null`, they would then need to remove it to avoid an error when upgrading. 

Certainly, users that are relying on that variable and setting it to `true`, they're going to run into an problem with that feature being deprecated at the AWS API. They've got some work anyway.

Anyway, just my two cents. I always pin module versions and test updates, so I'm happy as long as the deprecation warning goes away. 😛
