### ISSUE TITLE
Variable Validation and Type Constraints

### ISSUE THREAD

**Issue by entscheidungsproblem** [terraform-aws-modules/terraform-aws-vpc#831]
## Is your request related to a problem? Please describe.
It would be helpful to have [variable validation](https://developer.hashicorp.com/terraform/language/expressions/custom-conditions#input-variable-validation) and [preconditions](https://developer.hashicorp.com/terraform/language/expressions/custom-conditions#preconditions-and-postconditions) to ensure that the inputs are correctly configured before applying.

## Describe the solution you'd like.
Updating to to [Terraform 1.3.0+](https://github.com/hashicorp/terraform/blob/v1.3/CHANGELOG.md) to be able to use [optional variables for objects](https://developer.hashicorp.com/terraform/language/expressions/type-constraints#optional-object-type-attributes). This allows for variable validation on values in objects, even if they are not provided.

## Additional context
- I have started some work locally and will create a PR soon.

**Comment by antonbabenko** [comment]
Hi Patrick,

This module, as well as the rest of [terraform-aws-modules](https://github.com/terraform-aws-modules) have lower Terraform version requirements because there is almost no need for us to bump it and drop support for customers using Terraform 1.0 (or even 0.13 in some cases). Maintaining multiple versions is too much work for the maintainers.

We have been delaying rushing the introduction of the newest features added into Terraform because some of them had side effects (aka `bugs` and `limitations`) when used in the modules.

There should be significant benefits for the module users when we upgrade the Terraform version significantly.

In the past, we had just a few significant upgrades of the Terraform version requirements - from 0.11 to 0.12, from 0.12 to 0.13.1, and from 0.13.1 to 1.0 (ongoing).

Let's leave this issue open for a while if anyone has more thoughts.
