### ISSUE TITLE
How to change a subnet from private to public

### ISSUE THREAD

**Issue by thebigcosinus** [terraform-aws-modules/terraform-aws-vpc#890]
Hi,

How can I change a subnet from private to public in same AZ without destroying EC2 in the subnet ?

Regards

**Comment by antonbabenko** [comment]
The main difference between public and private subnets is the availability of a NAT gateway.

If you change arguments from `private_subnets` to `public_subnets`, Terraform will try to delete and recreate a lot of resources (e.g. subnets, routing tables, routes, etc).

To avoid the destruction of your resources, you will have to instruct Terraform to change the names of the resources instead of dropping them entirely, for example:
```
$ terraform state mv "module.vpc.aws_route_table.private[0]" "module.vpc.aws_route_table.public[0]"
# and so on...
```

It can take some time and effort to make it, but it is doable.

PS: Please ask follow-up questions on https://discuss.hashicorp.com since this is not related to the behavior of the module itself but how Terraform works.
