### ISSUE TITLE
Can you extract the subnet-ids from the VPC module?

### ISSUE THREAD

**Issue by yannickvranckx** [terraform-aws-modules/terraform-aws-vpc#961]
## Description

Is there a possibility to extract the subnet-ids from the module when it is being deployed? 
For example: To create a Transit Gateway attachment to an existing Transit Gateway for example, as that resource needs subnet-ids to operate.

## Versions

- Module version [Required]: 5.0

- Terraform version: 1.5.2 - darwin_amd64

- Provider version(s): Installing hashicorp/aws v5.7.0...

## Reproduction Code [Required]

`
module "vpc" {
  source = "terraform-aws-modules/vpc/aws" #Source of the module

  name = var.name
  cidr = var.cidr

  azs             = var.azs
  private_subnets = var.private_subnets
  public_subnets  = var.public_subnets

  enable_nat_gateway        = false #Disable the NAT GW
  single_nat_gateway        = false #NAT not HA
  enable_vpn_gateway        = false
  enable_flow_log           = true #Enable flow logs
  flow_log_destination_type = "s3" # Set the destination
  flow_log_destination_arn  = resource.aws_s3_bucket.flow_logs.arn
  enable_dns_hostnames      = true
  enable_dns_support        = true
}
`

**Comment by trevorrea** [comment]
The module has outputs for this purpose. See https://github.com/terraform-aws-modules/terraform-aws-vpc#output_private_subnets and https://github.com/terraform-aws-modules/terraform-aws-vpc#output_private_subnets etc. etc.

**Comment by rjay98** [comment]
I'm using `cdktf` and I'm getting an error - instead of the `subnetIds` (e.g., `subnet-00XXXX`) the outputs are the IPv4 CIDRs (e.g., `10.0.1.0/24`)
<img width="337" alt="Screenshot 2023-07-29 at 6 45 23 PM" src="https://github.com/terraform-aws-modules/terraform-aws-vpc/assets/21977004/f7a89ec8-b7bd-401e-9edc-cfe1159d5c34">
<img width="600" alt="Screenshot 2023-07-29 at 6 46 16 PM" src="https://github.com/terraform-aws-modules/terraform-aws-vpc/assets/21977004/8883e36e-98e0-44ed-ba6b-e8354bf6d595">
