### ISSUE TITLE
Add support for secondary IPs for AWS NAT Gateway

### ISSUE THREAD

**Issue by marcincuber** [terraform-aws-modules/terraform-aws-vpc#966]
Add support for secondary IPs to be associated with AWS NAT Gateway/s. This has been released as part of aws terraform provider https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.10.0

**Comment by rajcheval** [comment]
Yes we need this as well. 

Since the module did not support assigning secondary IPs I used Terraform to create 3 new elastic IP's for each of my gateway.
I used the AWS console to manually assigned these secondary IP addresses to the nat gateways.
When applying an unrelated change to the NAT Gateway I noticed that my NAT gateways were destroyed. 
This will cause an outage in a real-world scenario.
When the NAT gateways were re-created the secondary IP addresses were removed.
